version: "3.9"
services:
  backend:
    image: ${REGISTRY}/azimuth_${DEVICE}:${BACKEND_VERSION}
    environment:
      - "CFG_PATH=${CFG_PATH}"
      - "SENTENCE_TRANSFORMERS_HOME=/azimuth_shr/sentence_transformers"
      - "TFHUB_CACHE_DIR=/azimuth_shr/tf_hub"
      - "TH"
      - "TEMP"
      - "NAME"
      - "PERTURBATION_TESTING"
      - "SIMILARITY"
    ports:
      - "8091:8091"
    volumes:
    - ./config:/config
    - ./azimuth_shr:/azimuth_shr
    - ./cache:/cache
  web:
    image: "${REGISTRY}/azimuth_app:${FRONTEND_VERSION}"
    command:
      - node
      - ./server.js
    environment:
      - "PORT=8080"
    ports:
      - "8080:8080"
